I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/prologue.rpy", line 1372, in script
    Kalvin "Anyways, the name is Kalvin."
Exception: Sayer 'Kalvin' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/prologue.rpy", line 1372, in script
    Kalvin "Anyways, the name is Kalvin."
  File "/Users/jennie/Desktop/renpy-8.3.4-sdk/renpy/ast.py", line 2579, in execute
    Say.execute(self)
  File "/Users/jennie/Desktop/renpy-8.3.4-sdk/renpy/ast.py", line 581, in execute
    who = eval_who(self.who, self.who_fast)
  File "/Users/jennie/Desktop/renpy-8.3.4-sdk/renpy/ast.py", line 470, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'Kalvin' is not defined.

macOS-15.0.1-arm64-arm-64bit arm64
Ren'Py 8.3.4.24120703
Chic Boutique 1.0
Tue May 27 16:48:43 2025
